### ISSUE TITLE
NameError: name '_CACHE' is not defined

### ISSUE THREAD

**Issue by mxwlsavard** [custom-components/sensor.personalcapital#5]
This appears in my Hass log after I install the sensor and enter my 2 factor authentication code. I am running hass Docker v0.84.6 but I also got the same error in 0.83 installed in a python virtual  environment. I tried to fix the code myself put python isn’t really my specialty. Let me know if you need any other info.

Log (redacted IDs in the first line):

> 2019-01-10 22:24:14 ERROR (MainThread) 
[homeassistant.components.websocket_api.http.connection.XXXXXXXXXXXXXXX]
 Error handling message: {'type': 'call_service', 'domain': 'configurator', 'service': 'configure', 'service_data': {'configure_id': 'XXXXXXXXXXXXXXX-1', 'fields': {'verification_code': 'XXXX'}}, 'id': 15}
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/components/websocket_api/decorators.py", line 16, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/app/homeassistant/components/websocket_api/commands.py", line 148, in handle_call_service
    connection.context(msg))
  File "/usr/src/app/homeassistant/core.py", line 1121, in async_call
    self._execute_service(handler, service_call))
  File "/usr/src/app/homeassistant/core.py", line 1143, in _execute_service
    await handler.func(service_call)
  File "/usr/src/app/homeassistant/components/configurator.py", line 221, in async_handle_service_call
    call.data.get(ATTR_FIELDS, {}))
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/personalcapital.py", line 82, in personalcapital_configuration_callback
    continue_setup_platform(hass, config, pc, add_devices, discovery_info)
  File "/config/custom_components/sensor/personalcapital.py", line 148, in continue_setup_platform
    sensors.append(PersonalCapitalNetWorthSensor(rest_pc, config[CONF_UNIT_OF_MEASUREMENT], categories))
  File "/config/custom_components/sensor/personalcapital.py", line 174, in __init__
    self.update()
  File "/config/custom_components/sensor/personalcapital.py", line 178, in update
    self._rest.update()
  File "/usr/src/app/homeassistant/util/__init__.py", line 324, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/sensor/personalcapital.py", line 312, in update
    self._pc.login(_CACHE[CONF_EMAIL], _CACHE[CONF_PASSWORD])
NameError: name '_CACHE' is not defined

**Comment by iantrich** [comment]
I'll check it out tonight. I don't have that error 🤷‍♂️

**Comment by mxwlsavard** [comment]
Here’s my configuration.yaml entry:
`   - platform: personalcapital
     email: !secret per_cap_email
     password: !secret per_cap_password`

And it looks like the hass Docker image has Python version 3.6.7. I can’t think what else could be different 🤔

**Comment by iantrich** [comment]
fixed in v0.0.5

**Comment by mxwlsavard** [comment]
Thank you!

**Comment by iantrich** [comment]
Should hopefully have a LL card out soon :)

**Comment by mxwlsavard** [comment]
Awesome!

I’m still having an issue unfortunately :/ I’ve removed the component and re-added it, along with deleting the pycache folder. Any ideas?

> Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyhap/accessory_driver.py", line 431, in send_events
    pushed = self.http_server.push_event(bytedata, client_addr)
  File "/usr/local/lib/python3.6/site-packages/pyhap/hap_server.py", line 874, in push_event
    self._handle_sock_timeout(client_addr, e)
  File "/usr/local/lib/python3.6/site-packages/pyhap/hap_server.py", line 828, in _handle_sock_timeout
    raise exception
  File "/usr/local/lib/python3.6/site-packages/pyhap/hap_server.py", line 871, in push_event
    client_socket.sendall(data)
  File "/usr/local/lib/python3.6/site-packages/pyhap/hap_server.py", line 670, in _wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyhap/hap_server.py", line 759, in sendall
    self.socket.sendall(result)
OSError: [Errno 9] Bad file descriptor

> Config directory: /config
2019-01-11 16:14:09 INFO (MainThread) [homeassistant.loader] Loaded websocket_api from homeassistant.components.websocket_api
2019-01-11 16:14:09 INFO (MainThread) [homeassistant.bootstrap] Home Assistant core initialized
2019-01-11 16:14:09 INFO (MainThread) [homeassistant.loader] Loaded logger from homeassistant.components.logger
2019-01-11 16:14:09 INFO (MainThread) [homeassistant.setup] Setting up logger
2019-01-11 16:14:10 WARNING (MainThread) [homeassistant.loader] You are using a custom component for sensor.personalcapital which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-01-11 16:14:20 WARNING (MainThread) [homeassistant.setup] Setup of homekit is taking over 10 seconds.
2019-01-11 16:14:28 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140629714718392] Error handling message: {'type': 'call_service', 'domain': 'configurator', 'service': 'configure', 'service_data': {'configure_id': '140632227930744-1', 'fields': {'verification_code': '6458'}}, 'id': 15}
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/components/websocket_api/decorators.py", line 16, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/app/homeassistant/components/websocket_api/commands.py", line 148, in handle_call_service
    connection.context(msg))
  File "/usr/src/app/homeassistant/core.py", line 1121, in async_call
    self._execute_service(handler, service_call))
  File "/usr/src/app/homeassistant/core.py", line 1143, in _execute_service
    await handler.func(service_call)
  File "/usr/src/app/homeassistant/components/configurator.py", line 221, in async_handle_service_call
    call.data.get(ATTR_FIELDS, {}))
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/personalcapital.py", line 82, in personalcapital_configuration_callback
    continue_setup_platform(hass, config, pc, add_devices, discovery_info)
  File "/config/custom_components/sensor/personalcapital.py", line 148, in continue_setup_platform
    sensors.append(PersonalCapitalNetWorthSensor(rest_pc, config[CONF_UNIT_OF_MEASUREMENT], categories))
  File "/config/custom_components/sensor/personalcapital.py", line 174, in __init__
    self.update()
  File "/config/custom_components/sensor/personalcapital.py", line 178, in update
    self._rest.update()
  File "/usr/src/app/homeassistant/util/__init__.py", line 324, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/sensor/personalcapital.py", line 313, in update
    self._pc.login(self._config[CONF_EMAIL], self._config[CONF_PASSWORD])
  File "/config/deps/lib/python3.6/site-packages/personalcapital/personalcapital.py", line 41, in login
    raise RequireTwoFactorException()
personalcapital.personalcapital.RequireTwoFactorException

**Comment by iantrich** [comment]
your login failed. do you have a `.pc-session` file? Delete it if you do

**Comment by mxwlsavard** [comment]
Hmm I don’t.

**Comment by mxwlsavard** [comment]
Hang on it might be a password issue.

**Comment by mxwlsavard** [comment]
That was it, at some I started using a password instead of a pin and I never changed my password in my secrets file. Thanks for your help! This is an awesome integration!
